# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 17:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='npo',
            managers=[
                ('npoManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
