# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sitevisitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='npo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
