# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnSupporter', models.BooleanField()),
                ('ageRange', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('supporterManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
