# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thankyou', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporter',
            name='city',
        ),
    ]
